### ISSUE TITLE
player does not look horizontally after respawn 

### ISSUE THREAD

**Issue by wzbbbb** [Farama-Foundation/ViZDoom#290]
I have been haunted by this issue for a while, and it feels like an issue from game.respawn_player().
It only happens when the player got killed while looking down or up.  Then when he is repawned, he stays looking up or down, an angle opposite to the angle when he got killed. 
This issue is not systematic, but show up often, like 1 in 10 respawn. 

Have you seen it before?

Edit: it seems it is not always in an opposite vertical angle after respawn, but definitely not horizontal.

**Comment by Miffyli** [comment]
Would you have any code to reproduce this issue with? Sounds like something that needs a very rough patch-around at the very least (something like setting the pitch to 0). I'll let @mwydmuch investigate deeper what could be the root cause.

**Comment by michaelkrax** [comment]
On the topic of pitch reset: is there a reason the ViZDoom API does not expose „centerview“ to reset the pitch to 0? I looked at the abstraction code and it seems this ZDoom command gets rejected on purpose.

Selfishly speaking I would prefer this to be available because at the moment I am keeping track of the sum of all pitch 
angle changes I make to have my own „centerview“ function. However, if a death wouldn‘t reset this to 0 reliably things could get awkward quickly. (However, so far I have not experienced this bug - or at least I did not notice)

**Comment by wzbbbb** [comment]
@Miffyli 
I don't really have any code ready to reproduce this, but the idea is not complicated. 
1. The goal is to start with normal "centerview" as @michaelkrax  mentioned. 
2. Then, lookup or down, until got killed.
3. After respawn, check if the play can still have a 'centerview'. 
In my case, more than 10% of the times, the player can not have centerview after respawn.

**Comment by michaelkrax** [comment]
@wzbbbb which map and which weapon(s) do you use? Does this happen in the default rocket deathmatch map of ViZDoom? I struggle to reproduce but I know that in map specific ACS code you can mess with the death sequence of actors. Just want to avoid we chase a map specific issue.

**Comment by wzbbbb** [comment]
@michaelkrax Thanks for checking this!  
I am using the "unknown" maps. I believe it happens to all 5 multi-player maps, and it happens to all weapons. 

doom_scenario_path = cig_with_unknown.wad

**Comment by mwydmuch** [comment]
Old issue, closing.
