### ISSUE TITLE
Save and restore game states?

### ISSUE THREAD

**Issue by biggzlar** [Farama-Foundation/ViZDoom#339]
Is there a way to save and restore the entire game state - like you would with a rom state? If not, would it be feasible to integrate with something like a `game.set_state()` method?

**Comment by Miffyli** [comment]
ViZDoom does not currently support that, and as far I have understood ZDoom's innards this would be rather difficult to setup. 

However I wonder if demos/replays could be used for this purpose: I.e. you record a demo, and resume the game to specific part of that demo. Quick googling seems indicate ZDoom does not support this out of the box, but with some luck it shouldn't be the hardest thing to implement.

**Comment by mwydmuch** [comment]
It should be possible to incorporate save/load functionality to add this feature. I will check if it will work fine.

**Comment by aklein1995** [comment]
Hi @mwydmuch, I would be very interested in this feature. Have you have time to implement that feature already? I am not able to find it. Thank you in advance!

**Comment by Miffyli** [comment]
@aklein1995 Unfortunately it has not been implemented yet, but we would be happy to accept PRs that add such functionality if anybody has time to implement it :)

**Comment by mwydmuch** [comment]
Hi @aklein1995, @Miffyli actually it's implemented, but it is not avilable in Python, I don't remember it was left in this unfinished/unreleased state, give me few hours to look into it.

**Comment by mwydmuch** [comment]
Ok @aklein1995, I've managed to fix some issues with it, so it can be used with a bit of precaution. 
Uninstall and install ViZDoom from the repo: `pip install git+https://github.com/mwydmuch/ViZDoom.git`
Then see https://github.com/mwydmuch/ViZDoom/blob/master/examples/python/save_load_game.py for the usage example. 

This is not well tested and I need to work on it a bit more to make it safer to use. Right now it can be safely used when combined with one map. Starting one map and then loading save from another one may cause problems since some of the internal variables like time, total reward, tic counts, time limits and many others are not reset/loaded when the game is loaded. To omit potential problems I advise calling `game.new_episode()` before `game.load()`, this should make it safer to use. As far as I remember the internal Doom rng state is saved and loaded, so this may impact the distribution of states, this is not that important in the case of Doom, but I think I should warn you.

I will try to refine this feature when I find some more time (probably not this week).

**Comment by mwydmuch** [comment]
As stated above, this feature was added and works but needs to be used carefully. Closing.
