### ISSUE TITLE
Timout when using multiplayer 

### ISSUE THREAD

**Issue by CaptainAwesomeee** [Farama-Foundation/ViZDoom#503]
Hello, 
I have a certain issue running ViZDoom in multiplayer mode.
Whenever I start a multiplayer game (if host or player joining doesn't matter), it tells me that it is waiting for players to connect. After about a minute of waiting, vizdoom closes itself with the following output: 

`Press 'Q' to abort network game synchronization.`
`Waiting for players: . [ 1/ 2]`
`Timeout, network game synchronization aborted.`
`Traceback (most recent call last):`
    `File "cig_multiplayer_host.py", line 46, in ⟨module⟩`
        `game.init()`
`vizdoom.vizdoom.ViZDoomUnexpectedExitException: Controlled ViZDoom instance exited unexpectedly.`

Even when I'm fast enough and connect a player to the host, so it should theoretically run, the game just loads for a while until it again stops with the same error. 

To test it, I just used the example script cig_multiplayer_host.py from the examples of ViZDoom itself.

The version for Vizdoom I am using is 1.1.13, but i've tried it with every other version down to 1.1.8.
I currently run it on Debian 10, but I have also experimented with openSUSE Leap 15.2 (where I have the same issue) and Windows 10 (where it actually runs, but I need it to run on my Debian system).

**Comment by Miffyli** [comment]
I sadly do not have a linux machine right here to try this out. Some suggestions:

- Could you try `multiple_instances` examples instead of the `cig_multiplayer_host.py`? The CIG ones are pretty old examples, might be obsolete by now.
- There might be some suggestions [here](https://github.com/mwydmuch/ViZDoom/issues/391), but those are mainly around multiprocessing and multiple servers/clients.
- You could check [sample-factory code on Doom multiplayer](https://github.com/alex-petrenko/sample-factory/tree/master/sample_factory/envs/doom/multiplayer) for hints.

**Comment by CaptainAwesomeee** [comment]
Thanks for the advice! I looked into your suggestions, and found some things:

- The `multiple_instances` example does run interestingly, but if I remove the thread for the second player (so the host should just wait) it again has the timeout occuring. I guess I just need to connect my agents fast enough then? :D But it would be nice to be able to start the agents without time pressure, especially since they need some time to start.
- The thread you suggensted did contain some very interesting information, but sadly didn't really talk about having timeouts as far as I could see. 
- That was a great tip. In the `doom_multiagent.py` file I found the parameter `+viz_connect_timeout` which I assume solves exactly my issue. I can see that it is by default set to 4 there (I assume this is in minutes?), but even adding that to my parameters it still ends in a timeout after the same amount of time. I tried it with different values from 0 up to 10000, all having the same result.

**Comment by Miffyli** [comment]
> I guess I just need to connect my agents fast enough then? :D But it would be nice to be able to start the agents without time pressure, especially since they need some time to start.

Good that there is some progress 😅 . I do not have further tips to give, other than a bad one ("could you modify your code so that all vizdoom instances launch roughly at the same time?" etc).

> I can see that it is by default set to 4 there (I assume this is in minutes?)

This should be in seconds, judging by the code, and by default it should be 60 (= one minute). I am still lacking a Linux machine to try things out, but given the simple logic behind this argument, it should work (if not, please raise a new issue ^^).

**Comment by mwydmuch** [comment]
Hello @CaptainAwesomeee, 

I confirm what @Miffyli said: `+viz_connect_timeout` argument specifies the timeout in seconds, by default value is 60 (1 minute). I checked it a moment ago with `cig_multiplayer.py` and `cig_multiplayer_host.py` examples and it works as expected (both timeout and the rest of the examples). And it can be set to some reasonably large number (e.g. 600 for 10 minutes).

I understand that you run a host process and then a separate agent process, right? Could you tell us more about how this agent process is run? Since the `multiple_instances.py` example works for you, maybe it's an issue that the network of one process is isolated from another (for example one process runs from a docker container and some ports are blocked for the container). You can set a specific port for connection using `-port` argument (default is 5029).

**Comment by CaptainAwesomeee** [comment]
Hi, 

thank you for your help. I still have the issue that the argument does not do anything for me. No matter what value I choose, it always results in a timeout after the default 60 seconds. 

Exactly as you assumed, I run the agent and the server seperate. My current setup is having the agent(s) run in docker containers (as you guessed correctly :D), and having the server run in another container, connecting them all with it's own network configuration. To test with the timeout issue I run everything natively though. I have the same problem when using containers. 

Since I have a working example now though, I guess I will try @Miffyli's approach of launching everything at the same time. 
Thank you both for your help!
